### ISSUE TITLE
Background on Mobile

### ISSUE THREAD

**Issue by talonbragg** [talonbragg/Custom-Markup#10]
Don't know what is happening but the background won't load on mobile, lets figure this out guys.

**Comment by PenetratingShot** [comment]
You want to use this to turn off parallax for mobile:

`@media only screen and (max-device-width: 1024px) {
    .bgimg-1{
        background-attachment: scroll;
    }
}`

**Comment by PenetratingShot** [comment]
Talon, I want you to center-align all of your headers and SVG icons. On mobile, it kinda cut off the screen.
