### ISSUE TITLE
Configure Viewport

### ISSUE THREAD

**Issue by talonbragg** [talonbragg/Custom-Markup#19]
Do this in the CSS for mobile.

**Comment by talonbragg** [comment]
Keep figuring out proper calculations for the viewport

**Comment by PenetratingShot** [comment]
Maybe 0.5

**Comment by PenetratingShot** [comment]
Oops

**Comment by PenetratingShot** [comment]
Wrong button lol

**Comment by PenetratingShot** [comment]
I know why, you didn't set the initial scale. That should've been on of the first things that you have done when configuring the viewport.
