### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by talonbragg** [talonbragg/Custom-Markup#20]
npm is working! Here is the proof:
<img src="https://custommarkup.ml/img/npmcustommarkup.PNG">

This shows that Custom Markup is install able because it is in the list of my installed modules.

**Comment by talonbragg** [comment]
WTFFFFFFFFF!!!!! Why is Wing In there!

**Comment by talonbragg** [comment]
Just uninstalled it lol

**Comment by PenetratingShot** [comment]
Nice!
