### ISSUE TITLE
XHTML

### ISSUE THREAD

**Issue by PenetratingShot** [talonbragg/Custom-Markup#28]
Should we use XHTML instead of HTML? XHTML is like HTML and XML mushed together. It has stricter rules and is the better option for services with SSL encryptions. It also offers better support for Internet Explorer.

Read more [here](http://stackoverflow.com/questions/1969290/what-is-the-difference-between-html-and-xhtml-extension-xhtml-is-a-markup-lan)

**Comment by PenetratingShot** [comment]
Oh, and consider serving the website off of a separate repo. Since we have enough content, it looks better if we have the backend stuff only

**Comment by talonbragg** [comment]
Did, I don't want to change Up the HTML to xhtml and I also don't want to switch the website over to another repo because that is to tedious to transfer the files. Done.
