### ISSUE TITLE
Server For Hosting

### ISSUE THREAD

**Issue by talonbragg** [talonbragg/Custom-Markup#36]
Name: **(Talon Bragg)**

  Issue (explained): 
  ------------------------
  **We should create a server for this so that it can be hosted directly. Mainly we should use Node.js. Otherwise, this looks good and we are almost to cdnjs!**
  ------------------------

  Email (work email):
  ------------------------
  pvpgamecrash@gmail.com (So that we can get back to you)
  ------------------------

**Comment by PenetratingShot** [comment]
Alright then 😄 

BTW if ur an admin, you can just delete the template... It's fine

**Comment by PenetratingShot** [comment]
Wait, so that you don't have to host from your comp?

**Comment by talonbragg** [comment]
Actually, npm already does this, cdn will too, so I can close this now.
