### ISSUE TITLE
This is not an HTML framework!

### ISSUE THREAD

**Issue by CopBill** [talonbragg/Custom-Markup#6]
## Hello, Cop Billhere.

I noticed some things wrong with your project

- HTML cant have frameworks, what would it do?
- If whatever you made just makes it easier to code in HTML, ex - allowing to code without typing tags, etc.
It is called a compiler...

Ways to fix this

1. Change the description

Also, you are continuously posting this project on HN, its a waste of everyone's time, just make a CSS framework.

**Comment by talonbragg** [comment]
shut up
I know its you kabir.

**Comment by talonbragg** [comment]
I hate you
