### ISSUE TITLE
Why are you posting this on Hacker News

### ISSUE THREAD

**Issue by CopBill** [talonbragg/Custom-Markup#7]
Why would you post this on Hacker News its not even good. I understand submitting it once, but multiple times if people didn't like it the first time they wont like it the second third of fourth. Also, it is actually against the site rules.

**Comment by talonbragg** [comment]
GO DIE IN A HOLE YOU ARE JUST BOT

**Comment by talonbragg** [comment]
The only time you ever do this with anybody is with me and shreyas now go away I know you have something to do with kabir.
